Feat/ui/components/responsive table
Panenco/panenco pull request #5
Opened 2020-08-31 08:52 UTC by SergeyMykytchyn

2020-09-02 15:55 UTC, klevytskyi requested changes

2020-09-02 15:55 UTC, klevytskyi commented on packages/ui/src/components/responsive-table/cell.tsx
> +      {icon}
Don't leave icon within td. Logic of showing/hiding arrow should be placed in table inself. Arrow should be put in separate td before mapping thought others.

2020-09-02 15:55 UTC, klevytskyi commented on packages/ui/src/components/responsive-table/table.tsx
> +        entries.map((entry) => {
```suggestion
        entries.forEach((entry) => {
```

2020-09-02 15:55 UTC, klevytskyi commented on packages/ui/src/components/responsive-table/table.tsx
> +    this.divSizeObserver = new ResizeObserver(
Also it's a good option to check horizontal resize only.

2020-09-03 14:51 UTC, SergeyMykytchyn commented on packages/ui/src/components/responsive-table/table.tsx
> +    this.divSizeObserver = new ResizeObserver(
Is it possible? As far as I know ResizeObserver fires when resize occures in any direction and it's not configurable

2020-09-07 07:26 UTC, klevytskyi commented on packages/ui/src/components/responsive-table/table.tsx
> +    this.divSizeObserver = new ResizeObserver(
Don't you just want to do `if ... { recalc() } `? otherwise your react component is recalculated every time

2020-09-08 18:36 UTC, klevytskyi approved these changes

2020-09-08 18:36 UTC, klevytskyi commented on packages/ui/src/components/responsive-table/cell.tsx
> +  );
```suggestion
  const content = component ? React.createElement(component, { row, rowIndex, cellIndex, accessor }) : (
    <>{row.data[accessor]}</>
  );
```

2020-09-08 18:36 UTC, klevytskyi commented on packages/ui/src/components/responsive-table/cell.tsx
> +  const Component = component;
```suggestion
```

2020-09-08 18:36 UTC, klevytskyi commented on packages/ui/src/components/responsive-table/table.tsx
> +import { TableInterface, TableProps, TableState, columnsPropType, rowsPropType, sortPropType } from './types';
```suggestion
import { TableProps, TableState, columnsPropType, rowsPropType, sortPropType } from './types';
```

2020-09-08 18:36 UTC, klevytskyi commented on packages/ui/src/components/responsive-table/table.tsx
> +
```suggestion
class Table extends React.Component<TableProps, TableState> {
  divRef: React.RefObject<HTMLElement>;

  divSizeObserver: ResizeObserver;

```

2020-09-08 18:36 UTC, klevytskyi commented on packages/ui/src/components/responsive-table/table.tsx
> +              return { ...currentState, containerWidth: this.divRef.current.offsetWidth };
```suggestion
              return { ...currentState, containerWidth: this?.divRef?.current?.offsetWidth };
```

2020-09-08 18:36 UTC, klevytskyi commented on packages/ui/src/components/responsive-table/table.tsx
> +    });
```suggestion
    this.divSizeObserver.observe(this?.divRef?.current as Element);
    this.resizeTable(this?.divRef?.current?.offsetWidth as number);
    this.setState((currentState) => {
      return { ...currentState, containerWidth: this?.divRef?.current?.offsetWidth };
    });
```

2020-09-08 18:36 UTC, klevytskyi commented on packages/ui/src/components/responsive-table/types.ts
> +}
```suggestion
```

2020-09-09 08:43 UTC, klevytskyi approved these changes
🔱

2020-09-09 08:43 UTC, merged